name: Deploy Project
on: push

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: lint
          run: npm run lint
        - name: Simulate
          run: echo "Linting"

    test:
      needs: lint
      runs-on: ubuntu-latest
      steps:
        - name: test
          run:  npm run test
        - name: Simulate
          run: echo "Testing"

    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: npm run build
        - name: Simulate
          run: echo "Building"
