name: Deploy Project
on: push

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: lint
          run: npm lint
        - name: Simulate
          run: echo "Linting"

    test:
      runs-on: ubuntu-latest
      steps:
        - name: test
          run:  npm test
        - name: Simulate
          run: echo "Testing"

    build:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: npm build
        - name: Simulate
          run: echo "Building"
